### ISSUE TITLE
Level selection menu breaks after completing a level

### ISSUE THREAD

**Issue by ravendevore** [Cone-Virus/Pynogram#4]
On the current commit of the multScreens branch, when a level is completed successfully, the button to go back to the main menu works, but selecting a new level no longer works. Clicking on "Start Game" does not display the difficulty selection screen; it instead skips straight to the level selection screen. Furthermore, the level selection buttons and quit button on this screen do not work; there no visible response to clicking them.

**Comment by Cone-Virus** [comment]
Fixed
